---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: comments-api
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: comments-api
  template:
    metadata:
      labels:
        app: comments-api
    spec:
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      terminationGracePeriodSeconds: 60
      containers:
      - name: app
        image: "comments-api-amd64:1.0"
        env:
        - name: DB_PORT
          value: "$DB_PORT"
        - name: DB_HOST
          value: "$DB_HOST"
        - name: DB_PASSWORD
          value: "$DB_PASSWORD"
        - name: DB_TABLE
          value: "$DB_TABLE"
        - name: DB_USERNAME
          value: "$DB_USERNAME"
        - name: SSL_MODE
          value: "$SSL_MODE"
        ports:
        - name: app
          containerPort: 8080
        livenessProbe:
          httpGet:
            path: /api/healthz
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 15
          timeoutSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: comments-api
spec:
  type: NodePort
  selector:
    service: comments-api
  ports:
  - protocol: TCP
    name: app
    port: 8080
    targetPort: app
  - name: postgres
    port: 5432
    targetPort: postgres
